### ISSUE TITLE
Trouble setting up next auth

### ISSUE THREAD

**Issue by QuickResolveAI** [dotneet/smart-chatbot-ui#2]
When I select the NEXTAUTH_ENABLED=true and use a https://generate-secret.vercel.app/32 for the NEXTAUTH_SECRET=dummy I get a blank screen when running the npm run dev.

Would it be okay if you do a tutorial on how to get this up and running?

**Comment by dotneet** [comment]
@QuickResolveAI 

Unlike chatbot-ui, smart-chatbot-ui requires MongoDB.
So, unfortunately, it is currently not possible to run it just by deploying to Vercel.

If you want to run smart-chatbot-ui in Vercel, you should be able to use MongoDB Atlas.
https://vercel.com/integrations/mongodbatlas

**Comment by dotneet** [comment]
@GEMTechnologies 
Here is the easiest way.
https://github.com/dotneet/smart-chatbot-ui#deploy

To publish a service to internet, you need to sign up for IaaS or VPS like AWS or GCP or Linode and set up the servers and DNS.

Do you need instructions that include even how to set these up?
If so, it is difficult to give you a set-up procedure because the procedure varies depending on which infrastructure service you choose.

**Comment by dotneet** [comment]
@GEMTechnologies Here is the prompt that generate the way to deploy smart-chatbot-ui to Linode. ChatGPT will be your partner.

```
How can I deploy a service that uses nodejs and MongoDB to Linode and publish it to the internet?
The files needed to start this service can be obtained with the following command.

`git clone git@github.com:dotneet/smart-chatbot-ui.git` 

The service can be started with the `docker compose up -d` command, including MongoDB. docker-compose.yml is already provided.
```
